sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t davidka79/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "EBS-docker"
  env: "EBS-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-322431154880"
  bucket_path: "EBS-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
